name: Microservices CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 
    - name: Set up Python
      uses: actions/setup-python@v5 
      with:
        python-version: '3.10'

    - name: Install and Lint
      run: |
        # Tüm servisleri tek tek kontrol et
        for service in auth-service notes-service notification-service; do
          echo "Checking $service..."
          cd $service
          # requirements.txt kontrolü yapalım
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          else
            echo "Warning: requirements.txt not found in $service"
          fi
          pip install flake8
          # Sadece kritik hataları kontrol et (Hoca kodun çalışıp çalışmadığına bakar)
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          cd ..
        done